KaSheaCosmetics_base/urls.py
# KaSheaCosmetics_base\urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

app_name = "KaSheaCosmetics_base"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("KaSheaCosmetics_home.urls")),
    path("", include("KaSheaCosmetics_products.urls")),
    path("", include("KaSheaCosmetics_cart.urls")),
    path("", include("KaSheaCosmetics_subscriptions.urls")),
    path("", include("KaSheaCosmetics_checkout.urls")),
    path("orders/", include("KaSheaCosmetics_orders.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

KaSheaCosmetics_cart/urls.py
# KaSheaCosmetics_cart\urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

app_name = "KaSheaCosmetics_cart"

urlpatterns = [
    path("shopping-cart/", views.shopping_cart, name="shopping-cart"),
    path("add-to-cart/<int:product_id>/", views.add_to_cart, name="add-to-cart"),
    path(
        "update-cart-quantity/", views.update_cart_quantity, name="update-cart-quantity"
    ),
    path("delete-from-cart/", views.delete_from_cart, name="delete-from-cart"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/commons/cart-modal.html
{% load static %}

<div id="shoppingCart" data-bs-scroll="false" class="offcanvas offcanvas-end">
    <div class="offcanvas-header fs-4">
        <h4 class="offcanvas-title fw-semibold">Shopping Bag</h4>
        <button type="button" class="btn-close btn-close-bg-none" data-bs-dismiss="offcanvas" aria-label="Close">
            <i class="far fa-times"></i>
        </button>
    </div>
    <div class="offcanvas-body me-xl-auto pt-0 mb-2 mb-xl-0">
        <form class="table-responsive-md shopping-cart pb-8 pb-lg-10">
            <table class="table table-borderless">
                <thead>
                    <tr class="fw-500">
                        <td colspan="3" class="border-bottom pb-6"><i
                                class="far fa-check fs-12px border me-4 px-2 py-1 text-body-emphasis border-dark rounded-circle"></i>
                            Your cart is saved for the next <span class="text-body-emphasis">4m34s</span></td>
                    </tr>
                </thead>
                <tbody>
                    <tr class="position-relative">
                        <td class="align-middle text-center">
                            <a href="#" class="d-block clear-product">
                                <i class="far fa-times"></i>
                            </a>
                        </td>
                        <td class="shop-product">
                            <div class="d-flex align-items-center">
                                <div class="me-6">
                                    <img src="../assets/images/products/product-03-75x100.jpg" width="60" height="80"
                                        alt="natural coconut cleansing oil">
                                </div>
                                <div class>
                                    <p class="card-text mb-1">
                                        <span class="fs-13px fw-500 text-decoration-line-through pe-3">$39.00</span>
                                        <span class="fs-15px fw-bold text-body-emphasis">$29.00</span>
                                    </p>
                                    <p class="fw-500 text-body-emphasis">Natural Coconut Cleansing Oil</p>
                                </div>
                            </div>
                        </td>
                        <td class="align-middle p-0">
                            <div class="input-group position-relative shop-quantity">
                                <a href="#" class="shop-down position-absolute z-index-2"><i
                                        class="far fa-minus"></i></a>
                                <input name="number[]" type="number"
                                    class="form-control form-control-sm px-6 py-4 fs-6 text-center border-0" value="1"
                                    required>
                                <a href="#" class="shop-up position-absolute z-index-2"><i class="far fa-plus"></i>
                                </a>
                            </div>
                        </td>
                    </tr>
                    <tr class="position-relative">
                        <td class="align-middle text-center">
                            <a href="#" class="d-block clear-product">
                                <i class="far fa-times"></i>
                            </a>
                        </td>
                        <td class="shop-product">
                            <div class="d-flex align-items-center">
                                <div class="me-6">
                                    <img src="../assets/images/products/product-06-75x100.jpg" width="60" height="80"
                                        alt="natural coconut cleansing oil">
                                </div>
                                <div class>
                                    <p class="card-text mb-1">
                                        <span class="fs-13px fw-500 text-decoration-line-through pe-3">$39.00</span>
                                        <span class="fs-15px fw-bold text-body-emphasis">$29.00</span>
                                    </p>
                                    <p class="fw-500 text-body-emphasis">Super Pure</p>
                                </div>
                            </div>
                        </td>
                        <td class="align-middle p-0">
                            <div class="input-group position-relative shop-quantity">
                                <a href="#" class="shop-down position-absolute z-index-2"><i
                                        class="far fa-minus"></i></a>
                                <input name="number[]" type="number"
                                    class="form-control form-control-sm px-6 py-4 fs-6 text-center border-0" value="1"
                                    required>
                                <a href="#" class="shop-up position-absolute z-index-2"><i class="far fa-plus"></i>
                                </a>
                            </div>
                        </td>
                    </tr>
                    <tr class="position-relative">
                        <td class="align-middle text-center">
                            <a href="#" class="d-block clear-product">
                                <i class="far fa-times"></i>
                            </a>
                        </td>
                        <td class="shop-product">
                            <div class="d-flex align-items-center">
                                <div class="me-6">
                                    <img src="../assets/images/products/product-09-75x100.jpg" width="60" height="80"
                                        alt="natural coconut cleansing oil">
                                </div>
                                <div class>
                                    <p class="card-text mb-1">
                                        <span class="fs-13px fw-500 text-decoration-line-through pe-3">$39.00</span>
                                        <span class="fs-15px fw-bold text-body-emphasis">$29.00</span>
                                    </p>
                                    <p class="fw-500 text-body-emphasis">Cleansing Balm</p>
                                </div>
                            </div>
                        </td>
                        <td class="align-middle p-0">
                            <div class="input-group position-relative shop-quantity">
                                <a href="#" class="shop-down position-absolute z-index-2"><i
                                        class="far fa-minus"></i></a>
                                <input name="number[]" type="number"
                                    class="form-control form-control-sm px-6 py-4 fs-6 text-center border-0" value="1"
                                    required>
                                <a href="#" class="shop-up position-absolute z-index-2"><i class="far fa-plus"></i>
                                </a>
                            </div>
                        </td>
                    </tr>
                </tbody>
            </table>
        </form>
    </div>
    <div class="offcanvas-footer flex-wrap">
        <div class="d-flex align-items-center justify-content-between w-100 mb-5">
            <span class="text-body-emphasis">Total price:</span>
            <span class="cart-total fw-bold text-body-emphasis">$106.00</span>
        </div>
        <a href="../shop/checkout.html" class="btn btn-dark w-100 mb-7" title="Check Out">Check Out</a>
        <a href="{% url 'KaSheaCosmetics_cart:shopping-cart' %}" class="btn btn-outline-dark w-100" title="View shopping cart">View
            shopping cart</a>
    </div>
</div>

templates/commons/footer_1.html
{% load static %}

<footer class="pt-16 py-lg-13 pb-16 footer">
    <div class="border-bottom pb-7 pb-lg-8">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-4 col-12 mb-lg-0 mb-11 px-0">
                    <ul class="list-inline fs-15px text-center text-lg-start mb-0">
                        <li class="list-inline-item me-9 pe-2"><a href="#" class="text-body-emphasis">About Us</a>
                        </li>
                        <li class="list-inline-item me-9 pe-2"><a href="#" class="text-body-emphasis">FAQs</a></li>
                        <li class="list-inline-item"><a href="#" class="text-body-emphasis">Shipping &amp; Return
                                Policy</a>
                        </li>
                    </ul>
                </div>
                <div class="col-lg-4 col-12 mb-lg-0 mb-11">
                    <div class="mx-auto text-center">
                        <img class="light-mode-img img-fluid"
                        src="{% static 'images/logo_black.svg' %}" width="192"
                            height="28" alt="Ka'Shea Cosmetics">
                    
                    </div>
                </div>
                <div class="col-lg-4 col-12 px-0">
                    <ul class="list-inline fs-15px text-center text-lg-end mb-0">
                        <li class="list-inline-item me-9 pe-2"><a href="#" class="text-body-emphasis">Accessibility</a>
                        </li>
                        <li class="list-inline-item me-9 pe-2"><a href="#" class="text-body-emphasis">Contact Us</a>
                        </li>
                        <li class="list-inline-item"><a href="#" class="text-body-emphasis">Blog</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="pt-9 pt-lg-8">
        <div class="container">
            <div class="row align-items-center ">
                <div
                    class="col-12 col-md-6 d-flex align-items-center justify-content-center justify-content-md-start px-0">
                    <p class="mb-0">© Ka'Shea Cosmetics 2025</p>
                    <ul class="list-inline fs-18px ms-6 mb-0">
                        <li class="list-inline-item me-8">
                            <a href="#"><i class="fab fa-twitter"></i></a>
                        </li>
                        <li class="list-inline-item me-8">
                            <a href="#"><i class="fab fa-facebook-f"></i></a>
                        </li>
                        <li class="list-inline-item me-8">
                            <a href="#"><i class="fab fa-instagram"></i></a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#"><i class="fab fa-youtube"></i></a>
                        </li>
                    </ul>
                </div>
                <div class="col-12 col-md-6 text-center text-md-end mt-8 mt-md-0 px-0">
                    <img src="#" data-src="{% static 'images/home/img_1.png' %}" width="313" height="28" alt="Paypal"
                        class="img-fluid lazy-image">
                </div>
            </div>
        </div>
    </div>
</footer>

templates/commons/footer_2.html
{% load static %}

<footer class="pt-15 pt-lg-20 pb-16 footer bg-section-4">
    <div class="container container-xxl pt-4">
        <div class="row">
            <div class="col-lg col-md-4 col-12 mb-11 mb-lg-0 fs-14px">
                <h3 class="fs-5 mb-6 ">Company</h3>
                <p class="pe-xl-18 lh-2">
                    Find a location nearest you. See <a class="" href="#"><u class="fw-medium">Our Stores</u></a>
                </p>
                <p class="mb-0 lh-2"><strong class="text-body-emphasis">+391 (0)35 2568 4593</strong>
                    <br>
                    KaSheaCosmetics@outlook.com
                </p>
            </div>
            <div class="col-lg col-md-4 col-12 mb-11 mb-lg-0">
                <h3 class="fs-5 mb-6 ">Useful links</h3>
                <ul class="list-unstyled mb-0 fw-medium ">
                    {% for side_nav_cat in sidenav_product_categories %}
                    <li class="pt-3 mb-4">
                        <a href="#" title="New Products" class="text-body">
                            {{ side_nav_cat.category_name }}
                            
                        </a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="col-lg col-md-4 col-12 mb-11 mb-lg-0">
                <h3 class="fs-5 mb-6 ">Information</h3>
                <ul class="list-unstyled mb-0 fw-medium ">
                    <li class="pt-3 mb-4">
                        <a href="#" title="Start a Return" class="text-body">Start a Return</a>
                    </li>
                    <li class="pt-3 mb-4">
                        <a href="#" title="Contact Us" class="text-body">Contact Us</a>
                    </li>
                    <li class="pt-3 mb-4">
                        <a href="#" title="Shipping FAQ" class="text-body">Shipping FAQ</a>
                    </li>
                    <li class="pt-3 mb-4">
                        <a href="#" title="Terms &amp; Conditions" class="text-body">Terms &amp; Conditions</a>
                    </li>
                    <li class="pt-3 mb-4">
                        <a href="#" title="Privacy Policy" class="text-body">Privacy Policy</a>
                    </li>
                </ul>
            </div>
            <div class="col-lg-5 col-12 mb-11 mb-lg-0">
                <h3 class="mb-4 ">Subscribe To Our Newsletter.</h3>
                <p class="lh-2 ">Enter your email below to be the first to know about new collections and product
                    launches.</p>
                <form class=" pt-8">
                    <div class="input-group position-relative">
                        <input type="email" class="form-control bg-body rounded-left"
                            placeholder="Enter your email address">
                        <button type="submit" class="btn btn-dark btn-hover-bg-primary btn-hover-border-primary ms-0">
                            Subscribe
                        </button>
                    </div>
                </form>
            </div>
        </div>
        <div class="row align-items-center mt-0 mt-lg-20 pt-lg-4">
            <div class="col-sm-12 col-md-6 col-lg-4 d-flex align-items-center order-2 order-lg-1 fs-6 mt-8 mt-lg-0">
                <p class="mb-0">© Ka'Shea Cosmetics 2025</p>
                <ul class="list-inline fs-18px ms-6 mb-0">
                    <li class="list-inline-item me-8">
                        <a href="#"><i class="fab fa-twitter"></i></a>
                    </li>
                    <li class="list-inline-item me-8">
                        <a href="#"><i class="fab fa-facebook-f"></i></a>
                    </li>
                    <li class="list-inline-item me-8">
                        <a href="#"><i class="fab fa-instagram"></i></a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#"><i class="fab fa-youtube"></i></a>
                    </li>
                </ul>
            </div>
            <div class="col-sm-12 col-lg-4 text-md-center order-1 order-lg-2 ">
                <a class="d-inline-block" href="../">
                    <img class="img-fluid light-mode-img loaded"
                    src="{% static 'images/logo_black.svg' %}"
                        data-src="{% static 'images/logo_black.svg' %}" width="179" height="26"
                        alt="Ka'Shea Cosmetics" loading="lazy" data-ll-status="loaded">
                 
                </a>
            </div>
            <div class="col-sm-12 col-md-6 col-lg-4 order-3 text-sm-start text-lg-end mt-8 mt-lg-0">
                <img src="{% static 'images/home/img_1.png' %}" data-src="{% static 'images/home/img_1.png' %}" width="313"
                    height="28" alt="Paypal" class="img-fluid loaded" loading="lazy" data-ll-status="loaded">
            </div>
        </div>
    </div>
</footer>

templates/commons/mobile-nav.html
{% load static %}
<div class="navbar">
    <div id="offCanvasNavBar" class="offcanvas offcanvas-start" style="--bs-offcanvas-width: 310px">
        <div class="offcanvas-header bg-body-tertiary">
            <h3 class="offcanvas-title text-uppercase">Glowing</h3>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <hr class="mt-0">
        <div class="offcanvas-body pt-0 mb-2">
            <ul class="navbar-nav">
                <li class="nav-item transition-all-xl-1 py-0 dropdown dropdown-fullwidth">
                    <a class="nav-link d-flex justify-content-between position-relative text-uppercase fw-semibold ls-1 fs-15px dropdown-toggle"
                        href="/" id="menu-item-home-canvas" aria-haspopup="true"
                        aria-expanded="false">Home</a>
                 
                </li>
                <li class="nav-item transition-all-xl-1 py-0 dropdown">
                    <a class="nav-link d-flex justify-content-between position-relative text-uppercase fw-semibold ls-1 fs-15px dropdown-toggle"
                        href="#" data-bs-toggle="dropdown" id="menu-item-pages-canvas" aria-haspopup="true"
                        aria-expanded="false">Shop</a>
                    <ul class="dropdown-menu py-6" aria-labelledby="menu-item-pages-canvas">
                        <li class="dropend" aria-haspopup="true" aria-expanded="false">
                            <a class="dropdown-item pe-6 dropdown-toggle d-flex justify-content-between border-hover"
                                href="#" data-bs-toggle="dropdown" id="menu-item-blog-canvas">
                                <span class="border-hover-target">
                                    Bath Salts
                                </span>
                            </a>
                            <ul class="dropdown-menu py-6" aria-labelledby="menu-item-blog-canvas"
                                data-bs-popper="none">
                                <li>
                                    <a class="dropdown-item border-hover" href="./blog/grid.html">
                                        <span class="border-hover-target">
                                            Awaken
                                        </span>
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item border-hover" href="./blog/grid-sidebar.html">
                                        <span class="border-hover-target">
                                            Unwind
                                        </span>
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item border-hover" href="./blog/grid-sidebar.html">
                                        <span class="border-hover-target">
                                            Muscle Soothe
                                        </span>
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item border-hover" href="./blog/grid-sidebar.html">
                                        <span class="border-hover-target">
                                            Zen Night
                                        </span>
                                    </a>
                                </li>

                                <li class="dropdown-divider"></li>

                            </ul>
                        </li>
                        <li class="dropdown-divider"></li>
                        <li class="dropend" aria-haspopup="true" aria-expanded="false">
                            <a class="dropdown-item pe-6 dropdown-toggle d-flex justify-content-between border-hover"
                                href="#" data-bs-toggle="dropdown" id="menu-item-about-us-canvas">
                                <span class="border-hover-target">
                                    Whipped Body Butters
                                </span>
                            </a>
                            <ul class="dropdown-menu py-6" aria-labelledby="menu-item-about-us-canvas"
                                data-bs-popper="none">
                                <li>
                                    <a class="dropdown-item border-hover" href="./about-us-01.html">
                                        <span class="border-hover-target">Sweet Stuff</span>
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item border-hover" href="./about-us-02.html">
                                        <span class="border-hover-target">Citrus Notes</span>
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item border-hover" href="./about-us-02.html">
                                        <span class="border-hover-target">
                                            Zen Butter
                                        </span>
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item border-hover" href="./about-us-02.html">
                                        <span class="border-hover-target">
                                            Naked
                                        </span>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="dropend" aria-haspopup="true" aria-expanded="false">
                            <a class="dropdown-item pe-6 dropdown-toggle d-flex justify-content-between border-hover"
                                href="#" data-bs-toggle="dropdown" id="menu-item-contact-us-canvas">
                                <span class="border-hover-target">
                                    Body Scrubs
                                </span>
                            </a>
                            <ul class="dropdown-menu py-6" aria-labelledby="menu-item-contact-us-canvas"
                                data-bs-popper="none">
                                <li>
                                    <a class="dropdown-item border-hover" href="./contact-us-01.html">
                                        <span class="border-hover-target">
                                            Awaken
                                        </span>
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item border-hover" href="./contact-us-02.html">
                                        <span class="border-hover-target">
                                            Unwind
                                        </span>
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item border-hover" href="./contact-us-02.html">
                                        <span class="border-hover-target">
                                            Zen Night
                                        </span>
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item border-hover" href="./contact-us-02.html">
                                        <span class="border-hover-target">
                                            Naked
                                        </span>
                                    </a>
                                </li>
                            </ul>
                        </li>


                    </ul>
                </li>
           
            </ul>
        </div>
        <hr class="mb-0">
        <div class="offcanvas-footer bg-body-tertiary">
            © 2023 Glowing. <br>
            All rights reserved.
        </div>
    </div>
</div>

templates/commons/search-modal.html
{% load static %}

<div id="searchModal" data-bs-scroll="false" class="offcanvas offcanvas-top" style="--bs-offcanvas-height: auto">
    <div class="container-wide container-xxl">
        <nav class="navbar navbar-expand-xl px-0 py-6 py-xl-12 row align-items-start">
            <div class="col-xl-3 d-flex justify-content-center justify-content-xl-start">
                <a href="../" class="navbar-brand py-4 d-lg-inline-block">
                    <img src="{% static 'images/logo_black.svg' %}" height="50" alt="Glowing - Bootstrap 5 HTML Templates">
                </a>
            </div>
            <div class="col-xl-6 d-flex justify-content-center">
                <form class="w-xl-100 w-sm-75 w-100 mt-6 mt-xl-0 px-6 px-xl-0">
                    <div class="input-group mx-auto">
                        <input type="text" class="form-control form-control bg-transparent border-primary"
                            placeholder="Search product">
                        <div
                            class="form-control-append position-absolute end-0 top-0 bottom-0 d-flex align-items-center">
                            <button class="input-group-text bg-transparent border-0 px-0 me-6" type="submit">
                                <i class="far fa-search fs-5"></i>
                            </button>
                        </div>
                    </div>
                    <div class="d-flex align-items-center justify-content-center mt-6">
                        <p class="text-muted mb-0 mr-3">Popular Searches</p>
                        <nav class="nav">
                            <a class="nav-link text-decoration-underline py-0 px-4" href="#">T-Shirt</a>
                            <a class="nav-link text-decoration-underline py-0 px-4" href="#">Blue</a>
                            <a class="nav-link text-decoration-underline py-0 px-4" href="#">Jacket</a>
                        </nav>
                    </div>
                </form>
            </div>
            <div class="icons-actions col-xl-3 d-flex justify-content-end fs-28px text-body-emphasis">
                <div class="px-5 d-none d-xl-inline-block">
                    <a class="lh-1 color-inherit text-decoration-none" href="#" data-bs-toggle="modal"
                        data-bs-target="#signInModal">
                        <svg class="icon icon-user-light">
                            <use xlink:href="#icon-user-light"></use>
                        </svg>
                    </a>
                </div>
                <div class="px-5 d-none d-xl-inline-block">
                    <a class="position-relative lh-1 color-inherit text-decoration-none" href="../shop/wishlist.html">
                        <svg class="icon icon-star-light">
                            <use xlink:href="#icon-star-light"></use>
                        </svg>
                        <span
                            class="badge bg-dark text-white position-absolute top-0 start-100 translate-middle mt-4 rounded-circle fs-13px p-0 square"
                            style="--square-size: 18px">3</span>
                    </a>
                </div>
                <div class="px-5 d-none d-xl-inline-block">
                    <a class="position-relative lh-1 color-inherit text-decoration-none" href="#"
                        data-bs-toggle="offcanvas" data-bs-target="#shoppingCart" aria-controls="shoppingCart"
                        aria-expanded="false">
                        <svg class="icon icon-star-light">
                            <use xlink:href="#icon-shopping-bag-open-light"></use>
                        </svg>
                        <span
                            class="badge bg-dark text-white position-absolute top-0 start-100 translate-middle mt-4 rounded-circle fs-13px p-0 square"
                            style="--square-size: 18px">3</span>
                    </a>
                </div>
            </div>
        </nav>
    </div>
</div>