KaSheaCosmetics_base/urls.py
# KaSheaCosmetics_base\urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

app_name = "KaSheaCosmetics_base"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("KaSheaCosmetics_home.urls")),
    path("", include("KaSheaCosmetics_products.urls")),
    path("", include("KaSheaCosmetics_cart.urls")),
    path("", include("KaSheaCosmetics_subscriptions.urls")),
    path("", include("KaSheaCosmetics_checkout.urls")),
    path("orders/", include("KaSheaCosmetics_orders.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

KaSheaCosmetics_products/urls.py
# KaSheaCosmetics_products\urls.py
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.urls import path

app_name = "KaSheaCosmetics_products"

urlpatterns = [
    path("products/", views.product_list, name="product_list"),
    path(
        "products/category/<slug:category_slug>/",
        views.product_list,
        name="product_by_category",
    ),
    path("products/<int:product_id>/", views.product_detail, name="product_detail"),
    path("products/update-price/", views.update_price, name="update_price"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/products/includes/customer-reviews.html
{% load static %}
{% load custom_filters %}

<section class="container pt-15 pb-15 pt-lg-17 pb-lg-20">
    <div class="text-center">
        <h3 class="mb-12">Customer Reviews</h3>
    </div>
    <div class="mb-11">
        <div class=" d-md-flex justify-content-between align-items-center">

            <div class="text-md-end mt-md-0 mt-7">
                <a href="#customer-review" class="btn btn-outline-dark" data-bs-toggle="collapse" role="button"
                    aria-expanded="false" aria-controls="customer-review"><svg class="icon">
                        <use xlink:href="#icon-Pencil"></use>
                    </svg>
                    Leave A Review
                </a>
            </div>
        </div>
    </div>
    <div class="collapse mb-14" id="customer-review">
        <form class="product-review-form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row">
                <div class="col-sm-4">
                    <div class="form-group mb-7">
                        <label class="mb-4 fs-6 fw-semibold text-body-emphasis" for="reviewName">Name</label>
                        <input id="reviewName" class="form-control" type="text" name="name" required>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="form-group mb-4">
                        <label class="mb-4 fs-6 fw-semibold text-body-emphasis" for="reviewEmail">Email</label>
                        <input id="reviewEmail" type="email" name="email" class="form-control" required>
                    </div>
                </div>
            </div>
            <div>
                <p class="mt-4 mb-5 fs-6 fw-semibold text-body-emphasis">Your Rating*</p>
                <div class="form-group mb-6 d-flex justify-content-start">
                    <div class="rate-input">
                        <input type="radio" id="star5" name="product_rating" value="5" required>
                        <label for="star5" title="5 stars" class="mb-0 mr-1 lh-1">
                            <i class="far fa-star"></i>
                        </label>
                        <input type="radio" id="star4" name="product_rating" value="4">
                        <label for="star4" title="4 stars" class="mb-0 mr-1 lh-1">
                            <i class="far fa-star"></i>
                        </label>
                        <input type="radio" id="star3" name="product_rating" value="3">
                        <label for="star3" title="3 stars" class="mb-0 mr-1 lh-1">
                            <i class="far fa-star"></i>
                        </label>
                        <input type="radio" id="star2" name="product_rating" value="2">
                        <label for="star2" title="2 stars" class="mb-0 mr-1 lh-1">
                            <i class="far fa-star"></i>
                        </label>
                        <input type="radio" id="star1" name="product_rating" value="1">
                        <label for="star1" title="1 star" class="mb-0 mr-1 lh-1">
                            <i class="far fa-star"></i>
                        </label>
                    </div>
                </div>
            </div>
            <div class="form-group mb-7">
                <label class="mb-4 fs-6 fw-semibold text-body-emphasis" for="reviewTitle">Title of Review:</label>
                <input id="reviewTitle" type="text" name="review_title" class="form-control" required>
            </div>
            <div class="form-group mb-10">
                <label class="mb-4 fs-6 fw-semibold text-body-emphasis" for="reviewMessage">How was your overall
                    experience?</label>
                <textarea id="reviewMessage" class="form-control" name="review_content" rows="5" required></textarea>
            </div>
            <div class="form-group mb-7">
                <label class="mb-4 fs-6 fw-semibold text-body-emphasis" for="reviewAddPhoto">Add a Photo
                    (Optional):</label>
                <input type="file" name="image" class="form-control border" id="reviewAddPhoto">
            </div>
            <div class="d-flex">
                <button type="submit" class="btn btn-dark btn-hover-bg-primary btn-hover-border-primary fw-semibold">
                    Submit Now
                </button>
            </div>
        </form>
    </div>
    <!-- CUSTOMER REVIEWS -->
    <div class=" mt-12">
        <h3 class="fs-5">
            {{ review_count }} Review{{ review_count|pluralize }}
        </h3>
        <hr>
        <!-- REVIEWS -->
         {% for product_review in product_reviews %}
        <div class="border-bottom pb-7 pt-10">
            <div class="d-flex align-items-center mb-6">
                <div class="d-flex align-items-center fs-15px ls-0">
                    <div class="rating">
                        <div class="filled-stars">
                            {% for i in product_review.product_rating|range_filter %}
                                <span class="star">
                                    <svg class="icon star text-primary">
                                        <use xlink:href="#star"></use>
                                    </svg>
                                </span>
                            {% endfor %}
                        </div>
                        <div class="empty-stars">
                            {% get_range 5 as star_range %}
                            {% for i in star_range %}
                                {% if i >= product_review.product_rating %}
                                    <span class="star">
                                        <svg class="icon star-o">
                                            <use xlink:href="#star-o"></use>
                                        </svg>
                                    </span>
                                {% endif %}
                            {% endfor %}
                        </div>
                        
                        
                    </div>
                </div>
                <span class="fs-3px mx-5"><i class="fas fa-circle"></i></span>
                <span class="fs-14">{{ product_review.created_at|date:"l, F d" }}</span>
            </div>
            <div class="d-flex justify-content-start align-items-center mb-5">
                <img src="#" data-src="../assets/images/others/single-product-01.png"
                    class="me-6 lazy-image rounded-circle" width="60" height="60" alt="Avatar">
                <div class>
                    <h5 class="mt-0 mb-4 fs-14px text-uppercase ls-1">
                        {{ product_review.name }}
                    </h5>
                    <p class="mb-0">/ Orlando, FL</p>
                </div>
            </div>
            <p class="fw-semibold fs-6 text-body-emphasis mb-5">
                {{ product_review.review_title }}
            </p>
            <p class="mb-10 fs-6">{{ product_review.review_content }}</p>
            {% if product_review.image %}
            <img src="{{ product_review.image.url }}" alt="Review Image" style="max-width: 200px; height: auto;">
            {% endif %}
            <div class="d-flex justify-content-end align-items-center">
                <a href="#" class="fs-14px mb-0 text-secondary">Was This Review Helpful?</a>
                <p class="mb-0 ms-7 text-body-emphasis">
                    <svg class="icon icon-like align-baseline">
                        <use xlink:href="#icon-like"></use>
                    </svg>
                    10
                </p>
                <p class="mb-0 ms-6 text-body-emphasis">
                    <svg class="icon icon-unlike align-baseline">
                        <use xlink:href="#icon-unlike"></use>
                    </svg>
                    1
                </p>
            </div>
        </div>
        {% endfor %}
     
    </div>
    <nav class="d-flex mt-13 pt-3 justify-content-center" aria-label="pagination">
        <ul class="pagination m-0">
            <li class="page-item">
                <a class="page-link rounded-circle d-flex align-items-center justify-content-center" href="#"
                    aria-label="Previous">
                    <svg class="icon">
                        <use xlink:href="#icon-angle-double-left"></use>
                    </svg>
                </a>
            </li>
            <li class="page-item"><a class="page-link" href="#">1</a></li>
            <li class="page-item active"><a class="page-link" href="#">2</a></li>
            <li class="page-item"><a class="page-link" href="#">3</a></li>
            <li class="page-item"><a class="page-link" href="#">...</a></li>
            <li class="page-item"><a class="page-link" href="#">6</a></li>
            <li class="page-item">
                <a class="page-link rounded-circle d-flex align-items-center justify-content-center" href="#"
                    aria-label="Next">
                    <svg class="icon">
                        <use xlink:href="#icon-angle-double-right"></use>
                    </svg>
                </a>
            </li>
        </ul>
    </nav>
</section>

templates/products/includes/product-list-side-categories.html
{% load static %}
<div class="col-lg-3 d-lg-block d-none">
    <div class="position-sticky top-0">
        <aside class="primary-sidebar pe-xl-9 me-xl-2 mt-12 pt-2 mt-lg-0 pt-lg-0">
            <div class="widget widget-product-category">
                <h4 class="widget-title fs-5 mb-6">Category</h4>
                <!-- HERE LIES THE MAIN CATEGORIES -->
                {% for product_cat in product_categories %}
                <ul class="navbar-nav navbar-nav-cate" id="widget_product_category">
                    <li class="nav-item">
                        <a href="{% url 'KaSheaCosmetics_products:product_by_category' product_cat.category_url %}"
                           title="{{ product_cat.category_name }}"
                           class="text-reset position-relative d-block text-decoration-none text-body-emphasis-hover d-flex align-items-center text-uppercase fs-14px fw-semibold letter-spacing-5">
                            <span class="text-hover-underline me-2">
                                {{ product_cat.category_name }}
                            </span>
                            <span data-bs-toggle="collapse" data-bs-target="#cat_{{ product_cat.category_url }}"
                                  class="caret flex-grow-1 d-flex align-items-center justify-content-end collapsed">
                                <svg class="icon">
                                    <use xlink:href="#icon-plus"></use>
                                </svg>
                            </span>
                        </a>
                
                        <div id="cat_{{ product_cat.category_url }}" class="collapse show" data-bs-parent="#widget_product_category">
                            <ul class="navbar-nav nav-submenu ps-8">
                                {% for product in products %}
                                {% if product.category.id == product_cat.id %}
                                <li class="nav-item">
                                    <a class="text-reset position-relative d-block text-decoration-none text-body-emphasis-hover d-flex align-items-center"
                                       href="{% url 'KaSheaCosmetics_products:product_detail' product.id %}">
                                        <span class="text-hover-underline">
                                            {{ product.name }}
                                        </span>
                                    </a>
                                </li>
                                {% endif %}
                                {% endfor %}
                            </ul>
                        </div>
                    </li>
                </ul>
                <br>
                {% endfor %}
                


                <!-- HERE LIES THE MAIN CATEGORIES -->


            </div>
            <div class="widget widget-product-hightlight">
                <h4 class="widget-title fs-5 mb-6">Hightlight</h4>
                <ul class="navbar-nav navbar-nav-cate" id="widget_product_hightlight">
                    <li class="nav-item">
                        <a href="#" title="Best Seller"
                            class="text-reset position-relative d-block text-decoration-none text-body-emphasis-hover d-flex align-items-center"><span
                                class="text-hover-underline">Best Seller</span></a>
                    </li>
                    <li class="nav-item">
                        <a href="#" title="New Arrivals"
                            class="text-reset position-relative d-block text-decoration-none text-body-emphasis-hover d-flex align-items-center"><span
                                class="text-hover-underline">New Arrivals</span></a>
                    </li>
                    <li class="nav-item">
                        <a href="#" title="Sale"
                            class="text-reset position-relative d-block text-decoration-none text-body-emphasis-hover d-flex align-items-center"><span
                                class="text-hover-underline">Sale</span></a>
                    </li>
                    <li class="nav-item">
                        <a href="#" title="Hot Items"
                            class="text-reset position-relative d-block text-decoration-none text-body-emphasis-hover d-flex align-items-center"><span
                                class="text-hover-underline">Hot Items</span></a>
                    </li>
                </ul>
            </div>

            <div class="widget widget-product-size">
                <h4 class="widget-title fs-5 mb-6">Size</h4>
                <ul class="navbar-nav navbar-nav-cate" id="widget_product_size">
                    <li class="nav-item">
                        <a href="#" title="Single"
                            class="text-reset position-relative d-block text-decoration-none text-body-emphasis-hover d-flex align-items-center"><span
                                class="text-hover-underline">Single</span></a>
                    </li>
                    <li class="nav-item">
                        <a href="#" title="5 Pack"
                            class="text-reset position-relative d-block text-decoration-none text-body-emphasis-hover d-flex align-items-center"><span
                                class="text-hover-underline">5 Pack</span></a>
                    </li>
                    <li class="nav-item">
                        <a href="#" title="Full size"
                            class="text-reset position-relative d-block text-decoration-none text-body-emphasis-hover d-flex align-items-center"><span
                                class="text-hover-underline">Full size</span></a>
                    </li>
                    <li class="nav-item">
                        <a href="#" title="Mini size"
                            class="text-reset position-relative d-block text-decoration-none text-body-emphasis-hover d-flex align-items-center"><span
                                class="text-hover-underline">Mini size</span></a>
                    </li>
                </ul>
            </div>

            <div class="widget widget-tags">
                <h4 class="widget-title fs-5 mb-6">Tags</h4>
                <ul class="w-100 mt-n4 list-unstyled d-flex flex-wrap mb-0">
                    <li class="me-6 mt-4">
                        <a href="#" title="Cleansing"
                            class="text-reset d-block text-decoration-none text-body-emphasis-hover text-hover-underline">Cleansing</a>
                    </li>
                    <li class="me-6 mt-4">
                        <a href="#" title="Make up"
                            class="text-reset d-block text-decoration-none text-body-emphasis-hover text-hover-underline">Make
                            up</a>
                    </li>
                    <li class="me-6 mt-4">
                        <a href="#" title="eye cream"
                            class="text-reset d-block text-decoration-none text-body-emphasis-hover text-hover-underline">eye
                            cream</a>
                    </li>
                    <li class="me-6 mt-4">
                        <a href="#" title="nail"
                            class="text-reset d-block text-decoration-none text-body-emphasis-hover text-hover-underline">nail</a>
                    </li>
                    <li class="me-6 mt-4">
                        <a href="#" title="shampoo"
                            class="text-reset d-block text-decoration-none text-body-emphasis-hover text-hover-underline">shampoo</a>
                    </li>
                    <li class="me-6 mt-4">
                        <a href="#" title="coffee bean"
                            class="text-reset d-block text-decoration-none text-body-emphasis-hover text-hover-underline">coffee
                            bean</a>
                    </li>
                    <li class="me-6 mt-4">
                        <a href="#" title="healthy"
                            class="text-reset d-block text-decoration-none text-body-emphasis-hover text-hover-underline">healthy</a>
                    </li>
                    <li class="me-6 mt-4">
                        <a href="#" title="skin care"
                            class="text-reset d-block text-decoration-none text-body-emphasis-hover text-hover-underline">skin
                            care</a>
                    </li>
                    <li class="me-6 mt-4">
                        <a href="#" title="sale"
                            class="text-reset d-block text-decoration-none text-body-emphasis-hover text-hover-underline">sale</a>
                    </li>
                    <li class="me-6 mt-4">
                        <a href="#" title="Cosmetics"
                            class="text-reset d-block text-decoration-none text-body-emphasis-hover text-hover-underline">Cosmetics</a>
                    </li>
                    <li class="me-6 mt-4">
                        <a href="#" title="Natural cleansers"
                            class="text-reset d-block text-decoration-none text-body-emphasis-hover text-hover-underline">Natural
                            cleansers</a>
                    </li>
                    <li class="me-6 mt-4">
                        <a href="#" title="Organic"
                            class="text-reset d-block text-decoration-none text-body-emphasis-hover text-hover-underline">Organic</a>
                    </li>
                </ul>
            </div>
        </aside>
    </div>
</div>