KaSheaCosmetics_base/urls.py
# KaSheaCosmetics_base\urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

app_name = "KaSheaCosmetics_base"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("KaSheaCosmetics_home.urls")),
    path("", include("KaSheaCosmetics_products.urls")),
    path("", include("KaSheaCosmetics_cart.urls")),
    path("", include("KaSheaCosmetics_subscriptions.urls")),
    path("", include("KaSheaCosmetics_checkout.urls")),
    path("orders/", include("KaSheaCosmetics_orders.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

KaSheaCosmetics_products/urls.py
# KaSheaCosmetics_products\urls.py
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.urls import path

app_name = "KaSheaCosmetics_products"

urlpatterns = [
    path("products/", views.product_list, name="product_list"),
    path(
        "products/category/<slug:category_slug>/",
        views.product_list,
        name="product_by_category",
    ),
    path("products/<int:product_id>/", views.product_detail, name="product_detail"),
    path("products/update-price/", views.update_price, name="update_price"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/home/includes/home_header.html
{% load static %}
<header id="header"
    class="header header-14 header-sticky header-transparent header-sticky-smart disable-transition-all position-absolute start-0 end-0 z-index-5">
    <div class="sticky-area main-header unset-mode-when-sticky" data-bs-theme="light">
        <div class="container-wide container">
            <div class="nav navbar px-0 d-block px-xxl-12 py-7 py-xl-30px sticky-py-xl-8">
                <div class="d-flex align-items-center flex-nowrap">
                    <div class="w-50 d-flex align-items-center justify-content-start">
                        <a href="/" class="navbar-brand has-sticky-logo p-0">
                            <img class="light-mode-img"
                            src="{% static 'images/logo_black.svg' %}" width="250" height="55"
                                alt="Glowing - Bootstrap 5 HTML Templates">
                            <img class="dark-mode-img" src="{% static 'images/logo_black.svg' %}" width="250" height="55"
                                alt="Glowing - Bootstrap 5 HTML Templates">
                            <img class="sticky-logo sticky-logo-light" src="{% static 'images/logo_black.svg' %}" width="250"
                                height="55" alt="Glowing - Bootstrap 5 HTML Templates">
                            <img class="sticky-logo sticky-logo-dark" src="{% static 'images/logo_black.svg' %}"
                                width="250" height="55" alt="Glowing - Bootstrap 5 HTML Templates">
                        </a>
                    </div>
                    <div class="w-50 d-flex align-items-center justify-content-end">
                        <div class="color-modes position-relative px-5">
                     
                            <ul class="dropdown-menu dropdown-menu-end fs-14px" data-bs-popper="static">
                                <li>
                                    <button type="button" class="dropdown-item d-flex align-items-center active"
                                        data-bs-theme-value="light" aria-pressed="true">
                                        <svg class="bi me-4 opacity-50 theme-icon">
                                            <use href="#sun-fill"></use>
                                        </svg>
                                        Light
                                        <svg class="bi ms-auto d-none">
                                            <use href="#check2"></use>
                                        </svg>
                                    </button>
                                </li>
                                <li>
                                    <button type="button" class="dropdown-item d-flex align-items-center"
                                        data-bs-theme-value="dark" aria-pressed="false">
                                        <svg class="bi me-4 opacity-50 theme-icon">
                                            <use href="#moon-stars-fill"></use>
                                        </svg>
                                        Dark
                                        <svg class="bi ms-auto d-none">
                                            <use href="#check2"></use>
                                        </svg>
                                    </button>
                                </li>
                                <li>
                                    <button type="button" class="dropdown-item d-flex align-items-center"
                                        data-bs-theme-value="auto" aria-pressed="false">
                                        <svg class="bi me-4 opacity-50 theme-icon">
                                            <use href="#circle-half"></use>
                                        </svg>
                                        Auto
                                        <svg class="bi ms-auto d-none">
                                            <use href="#check2"></use>
                                        </svg>
                                    </button>
                                </li>
                            </ul>
                        </div>
                        <div class>
                            <button
                                class="navbar-toggler align-self-center  border-0 shadow-none px-0 canvas-toggle map[classWrapper:]"
                                type="button" data-bs-toggle="offcanvas" data-bs-target="#offCanvasNavBar"
                                aria-controls="offCanvasNavBar" aria-expanded="false" aria-label="Toggle Navigation">
                                <span class="fs-24 toggle-icon"></span>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

templates/home/includes/home_hot_products.html
{% load static %}
<style>
    img {
        opacity: 0.7;
        transition: 0.3s;
    }
    img:hover {
        opacity: 1;
    }
</style>

  <!-- HOT PRODUCT 1 -->
  <section class="container-fluid">
    <div class="row hero">
        <div data-animate="zoomIn" class="col-lg-6 bg-image hero-hot-product lazy-bg"
            data-bg-src="{% static 'images/home/homepage-bg-1.jpg' %}">
        </div>
        <div data-animate="zoomIn"
            class="col-lg-6 d-flex align-items-center py-16 mh-600 hero-hot-product bg-section-7">
            <div class="position-relative image-box-5 border-0 mx-auto">
                <div class="image-box-image d-flex justify-content-center position-relative">
                    <img
                    data-src="{% static 'images/home/Kashea_Zen-Night_Bath-Salts_TP.png' %}" class="img-fluid lazy-image"
                        width="350" height="251" alt="shroom serum" src="#" />
                </div>
                <div class="card-body text-center pt-13">
                    <h6
                        class="image-box-hot position-absolute font-primary start-50 text-nowrap mb-2 text-primary fw-normal fst-italic lh-1">
                        Hot Product</h6>
                    <h3 class="fs-2 text-uppercase mb-8">Bath Salts</h3>
                    <p class="mx-auto mb-7 fs-18px text-body" style="max-width: 390px">Try our soothing bath salts, perfect for a nice soak in the bath after a long hard day.</p>
                    <a href="{% url 'KaSheaCosmetics_products:product_list' %}"
                        class="fw-semibold text-body-emphasis text-decoration-none hero-link pb-3">
                        Shop Now
                        <svg class="icon icon-arrow-right">
                            <use xlink:href="#icon-arrow-right"></use>
                        </svg>
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- HOT PRODUCT 2 -->
<section class="container-fluid">
    <div class="row hero">
        <div data-animate="zoomIn" class="col-lg-6 bg-image hero-hot-product order-lg-1 lazy-bg"
            data-bg-src="{% static 'images/home/homepage-bg-2.jpg' %}"></div>
        <div data-animate="zoomIn"
            class="col-lg-6 d-flex align-items-center py-16 mh-600 hero-hot-product order-lg-0">
            <div class="position-relative image-box-5 border-0 mx-auto">
                <div class="image-box-image d-flex justify-content-center position-relative">
                    <img data-src="{% static 'images/home/Kashea_Awaken_Body Scrub.png' %}" class="img-fluid lazy-image"
                        width="350" height="251" alt="fancial cleanser" src="#" />
                </div>
                <div class="card-body text-center pt-13">
                    <h6
                        class="image-box-hot position-absolute font-primary start-50 text-nowrap mb-2 text-primary fw-normal fst-italic lh-1">
                        Hot Product</h6>
                    <h3 class="fs-2 text-uppercase mb-8">Body Scrubs</h3>
                    <p class="mx-auto mb-7 fs-18px" style="max-width: 390px">Pair Ka'Shea body scrubs with Ka'Shea bath salts. You'll skin will be smooth and thank you.</p>
                    <a href="{% url 'KaSheaCosmetics_products:product_list' %}"
                        class="fw-semibold text-body-emphasis text-decoration-none hero-link pb-3">
                        Shop Now
                        <svg class="icon icon-arrow-right">
                            <use xlink:href="#icon-arrow-right"></use>
                        </svg>
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>

templates/home/includes/home_special_offer_banner.html
{% load static %}
<section id="special_offer_save_on_sets_2" class="bg-section-2 ">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6 px-0 bg-image bg-col-lg-half-screen-left lazy-bg"
                data-bg-src="{% static 'images/home/homepage-bg-1.jpg' %}" data-animate="fadeInUp">
                <div class="py-25 my-xl-21 my-lg-8"></div>
            </div>
            <div class="col-lg-6 py-lg-10 py-16 ps-lg-10 ps-xl-18 order-2" data-animate="fadeInUp">
                <div class="text-left">
                    <p class="fs-15px mb-6 ls-1 text-body-emphasis fw-semibold">SPECIAL OFFER <span
                            class="badge bg-primary fs-15px py-3 px-4 ms-4">-20%</span></p>
                    <h2 class="mb-6">Don't Miss The Sale!</h2>
                    <p class="fs-18px w-md-70 w-lg-100 w-xl-75 mb-7 text-body">Made using clean, non-toxic
                        ingredients, our products are designed for everyone.</p>
                </div>
                <div class="d-flex countdown ms-n4 ms-md-n7" data-countdown="true"
                    data-countdown-end="Jan 27, 2025 18:24:25">
                    <div class="countdown-item text-center px-md-7 px-4 fs-1">
                        <span class="day fw-semibold text-primary font-primary"></span>
                    </div>
                    <div class="separate fw-semibold fs-1 text-primary">:</div>
                    <div class="countdown-item text-center px-md-7 px-4 fs-1">
                        <span class="hour fw-semibold text-primary font-primary"></span>
                    </div>
                    <div class="separate fw-semibold fs-1 text-primary">:</div>
                    <div class="countdown-item text-center px-md-7 px-4 fs-1">
                        <span class="minute fw-semibold text-primary font-primary"></span>
                    </div>
                    <div class="separate fw-semibold fs-1 text-primary">:</div>
                    <div class="countdown-item text-center px-md-7 px-4 fs-1">
                        <span class="second fw-semibold text-primary font-primary"></span>
                    </div>
                </div>
                <a href="{% url 'KaSheaCosmetics_products:product_list' %}"
                    class="mt-11 btn btn-dark btn-hover-text-light btn-hover-bg-primary btn-hover-border-primary shadow-sm">Everythings Half Price!</a>
            </div>
        </div>
    </div>
</section>